<?php

namespace AppBundle\Repository;

/**
 * BlogArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
